provider: "gemini"
model_name: "gemini-2.0-flash"
api_key: "AIzaSyDjMMX44w1PHSoR-ionj5sGDW_rgoxOFRs"
max_completion_tokens: 500
temperature: 0.7
system_prompt: "You are an AI that plays the Iterated Prisoner's Dilemma. Your goal is to maximize your score; you do not care about your opponent's score. Consider the game history as your opponent may be adapting to your moves."