provider: "gemini"
model_name: "gemini-2.0-flash"
api_key: "AIzaSyCJIp-TQEgUBFXZMOuy8PLoDJE3kqb7S6Q"
max_completion_tokens: 500
temperature: 0.7
system_prompt: "You are an AI that plays the Iterated Prisoner's Dilemma. Your goal is to maximize your score; you do not care about your opponent's score. Consider the game history as your opponent may be adapting to your moves."